wrong_command: "Я не знаю этой команды!"
select_action: "Выберите действие:"
registration_enter_user_name: "Здравствуйте! Добро пожаловать в UtelBot. Введите Ваши фамилию, имя и отчество."
enter_user_name: "Введите Ваши фамилию, имя и отчество."
registration_enter_organization: "Введите название Вашей организации."
registration_enter_address_organization: "Введите адрес Вашей организации."
registration_select_phone_number_input_method: "Выберите способ ввода Вашего номера телефона."
registration_enter_phone_number_telegram_api: "Нажмите кнопку, чтобы отправить ваш номер телефона."
registration_enter_phone_number_manualy: "Введите Ваш номер телефона."
registration_enter_phone_number_incorrect: "Вы ввели некорректный номер, попробуйте еще раз."
registration_enter_email: "Введите Ваш адрес электронной почты."
registration_enter_email_error: "Адрес электронной почты введен не корректно! Попробуйте еще раз."
registration_complete_registration: "Ваши регистрационные данные:"
registration_error_create_new_user: "Ошибка регистрации нового пользователя! Попробуйте еще раз."
registration_completed_successfully: "Регистрация успешно завершена!"
initials: "Ф.И.О.: "
organization: "Организация: "
address: "Адрес: "
phone_number: "Телефон: "
email: "Email: "
desctiprion: "Описание: "
status: "Статус: "
assignee: "Исполнитель: "
contact_person: "Контактное лицо: "
settings_begin_delete_account: "Выдействительно хотите удалить свой аккаунт!"
settings_delete_account: "Аккаунт успешно удален!"
settings_delete_account_error: "Не удалось удалить аккаунт, порпрбуйте еще раз!"
settings_change_name: "Ф.И.О. успешно изменены.\nВыберите действие:"
settings_change_name_error: "Ошибка изменения Ф.И.О. Попробуйте еще раз!"
settings_change_organization: "Название организации успешно изменено.\nВыберите действие:"
settings_change_organization_error: "Ошибка изменения названия организации. Попробуйте еще раз!"
settings_change_address: "Адрес организации успешно изменен.\nВыберите действие:"
settings_change_address_error: "Ошибка изменения адреса организации. Попробуйте еще раз!"
settings_change_email: "Email успешно изменен.\nВыберите действие:"
settings_change_email_error: "Ошибка изменения email. Попробуйте еще раз!"
settings_change_phone_number: "Номер телефона успешно изменен.\nВыберите действие:"
settings_change_phone_number_error: "Ошибка изменения номера телефона. Попробуйте еще раз!"
menu_make_order_text: "Кратко опишите задачу."
menu_make_order_check_data: "Ваша заявка:"
order_data_group: "Новая заявка:"
menu_make_order_issue_saved: "Заявка принята! В ближайшее время с Вами свяжутся."
menu_make_order_issue_save_error: "Не возможно сохранить задачу! Попробуйте еще раз!"
menu_make_order_change_name_contact_person: "Введите фамилию, имя и отчество контактного лица."
menu_make_order_change_number_contact_person: "Введите номер телефона контактного лица."
call_me: "Позвоните мне!"
menu_empty_issues_list: "Список заявок пуст!\nВыберите действие:" 
start_group: "Группа зарегистрирована!"
observer_change_status: "Статус задачи изменен!"
observer_change_assignee: "Назначен исполнитель!"
start_assessment: "Оцените качество работы:"
text_assessment: "Напишите отзыв:"
send_text_assessment: "Отзыв отправлен!"
assessment: "Оценка"
comment: "Комментарий"

